name: Domain Değişiklik Kontrolü

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 11 */9 * * *

jobs:
  DomainKontrol:
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      BRANCH_NAME: domain-degisikligi

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python 3.11.8 Yükle
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Python Sürümümü Göster
        run: python -c "import sys; print(sys.version)"

      - name: Gereksinimleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik cloudscraper

      - name: Betiği Çalıştır
        run: |
          python KONTROL.py

      - name: Değişiklik Kontrolü
        id: degisiklik_kontrol
        run: |
          if git diff --quiet .; then
            echo "degisiklik=false" >> $GITHUB_ENV
          else
            echo "degisiklik=true" >> $GITHUB_ENV
          fi

      - name: Branch Kontrolü ve Oluşturma
        run: |
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Branch zaten mevcut."
          else
            git config user.name "github-actions[bot]"
            git config user.email "203746723+github-actions[bot]@users.noreply.github.com"
            git checkout -b $BRANCH_NAME
            git push origin $BRANCH_NAME
          fi

      - name: Değişiklikleri Commit ve Push Et
        if: env.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "203746723+github-actions[bot]@users.noreply.github.com"
          git checkout $BRANCH_NAME
          git add -A
          git commit -m "♻️ Domain Değişikliği" \
                      -m "🔄 Otomatik domain güncellemeleri yapıldı." \
                      -m "Co-authored-by: github-actions[bot] <203746723+github-actions[bot]@users.noreply.github.com>" \
                      -m "Co-authored-by: primatzeka <primatzeka@users.noreply.github.com>"
          git push origin $BRANCH_NAME --force

      - name: Pull Request Oluştur
        if: env.degisiklik == 'true'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls \
            -d @- <<EOF
          {
            "title": "♻️ Domain Değişikliği",
            "head": "$BRANCH_NAME",
            "base": "master",
            "body": "🔄 Otomatik tespit edilen domain değişiklikleri uygulandı.\n\n📂 İlgili dosyalar güncellendi. Lütfen değişiklikleri gözden geçirin ve onaylayın."
          }
          EOF